[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scilib"
version = "0.1.0"
description = "High-Precision scientific calculations"
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy"]
license = {file = "LICENSE"}  # MIT License auto-detected

[project.optional-dependencies]
precision = ["gmpy2>=2.1.0"]  # FÃ¼r mpfr Nutzer
dev = ["pytest", "black"]

[project.urls]
Homepage = "https://github.com/SamsonandDelilah/SciLib"
